<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\TeacherValidation;
use App\Models\School;
use App\Models\JobFairEvent;
use App\Models\JobFairRegistration;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Create schools
        $schools = [
            [
                'school_name' => 'Lincoln High School',
                'school_type' => 'public',
                'district_name' => 'Austin Independent School District',
                'school_code' => 'LHS-TX-001',
                'address' => '7800 Berkman Drive',
                'city' => 'Austin',
                'state' => 'TX',
                'zip_code' => '78752',
                'phone' => '+1 512-555-1000',
                'email' => 'info@lincolnhs.edu',
                'website' => 'https://lincolnhs.edu',
                'principal_name' => 'Dr. Elizabeth Morrison',
                'principal_email' => 'e.morrison@lincolnhs.edu',
                'hr_contact_name' => 'Michael Stevens',
                'hr_contact_email' => 'hr@lincolnhs.edu',
                'hr_contact_phone' => '+1 512-555-1001',
                'grade_levels' => ['9-12', 'High School'],
                'total_students' => 1850,
                'total_teachers' => 120,
                'student_teacher_ratio' => 15.42,
                'subjects_needed' => ['Math', 'Science', 'Spanish', 'English'],
                'years_in_program' => 8,
                'teachers_hired_total' => 45,
                'teachers_hired_current_year' => 6,
                'positions_available' => 4,
                'required_certifications' => ['State Teaching License', 'Background Check'],
                'minimum_experience_years' => 2,
                'sponsors_visa' => true,
                'provides_housing_assistance' => true,
                'housing_details' => 'Housing stipend of $500/month available',
                'salary_range_min' => 45000,
                'salary_range_max' => 62000,
                'benefits_offered' => ['Health Insurance', 'Retirement Plan', 'Professional Development'],
                'is_active' => true,
                'is_verified' => true,
                'verification_date' => now()->subDays(30),
                'rating' => 4.6,
                'total_reviews' => 28,
            ],
            [
                'school_name' => 'Riverside Middle School',
                'school_type' => 'public',
                'district_name' => 'Portland Public Schools',
                'school_code' => 'RMS-OR-002',
                'address' => '4567 River Road',
                'city' => 'Portland',
                'state' => 'OR',
                'zip_code' => '97211',
                'phone' => '+1 503-555-2000',
                'email' => 'contact@riversidems.edu',
                'website' => 'https://riversidems.edu',
                'principal_name' => 'Jennifer Chang',
                'principal_email' => 'j.chang@riversidems.edu',
                'hr_contact_name' => 'Robert Martinez',
                'hr_contact_email' => 'hr@riversidems.edu',
                'hr_contact_phone' => '+1 503-555-2001',
                'grade_levels' => ['6-8', 'Middle School'],
                'total_students' => 920,
                'total_teachers' => 65,
                'student_teacher_ratio' => 14.15,
                'subjects_needed' => ['English', 'History', 'PE', 'Art'],
                'years_in_program' => 5,
                'teachers_hired_total' => 18,
                'teachers_hired_current_year' => 3,
                'positions_available' => 3,
                'required_certifications' => ['Teaching Certificate', 'First Aid'],
                'minimum_experience_years' => 1,
                'sponsors_visa' => true,
                'provides_housing_assistance' => false,
                'salary_range_min' => 42000,
                'salary_range_max' => 58000,
                'benefits_offered' => ['Health Insurance', 'Dental', 'Vision'],
                'is_active' => true,
                'is_verified' => true,
                'verification_date' => now()->subDays(45),
                'rating' => 4.8,
                'total_reviews' => 15,
            ],
            [
                'school_name' => 'Oakwood Elementary',
                'school_type' => 'public',
                'district_name' => 'Denver Public Schools',
                'school_code' => 'OES-CO-003',
                'address' => '1234 Oak Street',
                'city' => 'Denver',
                'state' => 'CO',
                'zip_code' => '80203',
                'phone' => '+1 303-555-3000',
                'email' => 'info@oakwoodes.edu',
                'website' => 'https://oakwoodes.edu',
                'principal_name' => 'Susan Wilson',
                'principal_email' => 's.wilson@oakwoodes.edu',
                'hr_contact_name' => 'David Brown',
                'hr_contact_email' => 'hr@oakwoodes.edu',
                'hr_contact_phone' => '+1 303-555-3001',
                'grade_levels' => ['K-5', 'Elementary'],
                'total_students' => 650,
                'total_teachers' => 45,
                'student_teacher_ratio' => 14.44,
                'subjects_needed' => ['Elementary Education', 'Special Ed', 'Music'],
                'years_in_program' => 10,
                'teachers_hired_total' => 32,
                'teachers_hired_current_year' => 4,
                'positions_available' => 5,
                'required_certifications' => ['Elementary Teaching License'],
                'minimum_experience_years' => 2,
                'sponsors_visa' => true,
                'provides_housing_assistance' => true,
                'housing_details' => 'Assistance with finding housing',
                'salary_range_min' => 40000,
                'salary_range_max' => 55000,
                'benefits_offered' => ['Health Insurance', 'Retirement', 'Tuition Reimbursement'],
                'is_active' => true,
                'is_verified' => true,
                'verification_date' => now()->subDays(60),
                'rating' => 4.7,
                'total_reviews' => 22,
            ],
            [
                'school_name' => 'St. Mary\'s Academy',
                'school_type' => 'private',
                'district_name' => null,
                'school_code' => 'SMA-FL-004',
                'address' => '8901 Academy Lane',
                'city' => 'Miami',
                'state' => 'FL',
                'zip_code' => '33125',
                'phone' => '+1 305-555-4000',
                'email' => 'admissions@stmarysacademy.edu',
                'website' => 'https://stmarysacademy.edu',
                'principal_name' => 'Dr. Maria Rodriguez',
                'principal_email' => 'm.rodriguez@stmarysacademy.edu',
                'hr_contact_name' => 'Patricia Johnson',
                'hr_contact_email' => 'hr@stmarysacademy.edu',
                'hr_contact_phone' => '+1 305-555-4001',
                'grade_levels' => ['K-12', 'All Levels'],
                'total_students' => 1200,
                'total_teachers' => 95,
                'student_teacher_ratio' => 12.63,
                'subjects_needed' => ['Spanish', 'Religion', 'Science', 'Math'],
                'years_in_program' => 6,
                'teachers_hired_total' => 22,
                'teachers_hired_current_year' => 5,
                'positions_available' => 6,
                'required_certifications' => ['Teaching Certificate', 'Catholic Education Certificate'],
                'minimum_experience_years' => 3,
                'sponsors_visa' => true,
                'provides_housing_assistance' => true,
                'housing_details' => 'School-owned apartments available',
                'salary_range_min' => 48000,
                'salary_range_max' => 68000,
                'benefits_offered' => ['Health Insurance', 'Retirement', 'Free Tuition for Children'],
                'is_active' => true,
                'is_verified' => true,
                'verification_date' => now()->subDays(20),
                'rating' => 4.9,
                'total_reviews' => 35,
            ],
            [
                'school_name' => 'Innovation Charter School',
                'school_type' => 'charter',
                'district_name' => 'Phoenix Charter Network',
                'school_code' => 'ICS-AZ-005',
                'address' => '2345 Innovation Boulevard',
                'city' => 'Phoenix',
                'state' => 'AZ',
                'zip_code' => '85012',
                'phone' => '+1 602-555-5000',
                'email' => 'info@innovationcharter.edu',
                'website' => 'https://innovationcharter.edu',
                'principal_name' => 'Dr. James Anderson',
                'principal_email' => 'j.anderson@innovationcharter.edu',
                'hr_contact_name' => 'Lisa White',
                'hr_contact_email' => 'hr@innovationcharter.edu',
                'hr_contact_phone' => '+1 602-555-5001',
                'grade_levels' => ['6-12', 'Middle-High School'],
                'total_students' => 780,
                'total_teachers' => 58,
                'student_teacher_ratio' => 13.45,
                'subjects_needed' => ['STEM', 'Technology', 'English', 'Social Studies'],
                'years_in_program' => 4,
                'teachers_hired_total' => 12,
                'teachers_hired_current_year' => 2,
                'positions_available' => 4,
                'required_certifications' => ['State License', 'STEM Certification'],
                'minimum_experience_years' => 1,
                'sponsors_visa' => true,
                'provides_housing_assistance' => false,
                'salary_range_min' => 43000,
                'salary_range_max' => 60000,
                'benefits_offered' => ['Health Insurance', 'Professional Development', 'Technology Stipend'],
                'is_active' => true,
                'is_verified' => true,
                'verification_date' => now()->subDays(15),
                'rating' => 4.5,
                'total_reviews' => 18,
            ],
        ];

        $createdSchools = [];
        foreach ($schools as $schoolData) {
            $createdSchools[] = School::create($schoolData);
        }

        // Create teachers
        $teachers = [
            ['name' => 'Prof. Ana Martinez', 'email' => 'ana.martinez@fpuna.edu.py', 'university' => 'Universidad Nacional', 'degree' => 'Licenciatura en Pedagogía', 'year' => 2015, 'experience' => 8, 'subjects' => ['Math', 'Physics']],
            ['name' => 'Prof. Carlos Benitez', 'email' => 'carlos.benitez@uca.edu.py', 'university' => 'Universidad Católica', 'degree' => 'Profesorado en Lengua Española', 'year' => 2017, 'experience' => 6, 'subjects' => ['Spanish', 'Literature']],
            ['name' => 'Prof. Maria Gonzalez', 'email' => 'maria.gonzalez@unae.edu.py', 'university' => 'Universidad Autónoma', 'degree' => 'Licenciatura en Ciencias', 'year' => 2014, 'experience' => 9, 'subjects' => ['Science', 'Biology']],
            ['name' => 'Prof. Diego Rojas', 'email' => 'diego.rojas@upap.edu.py', 'university' => 'Universidad Politécnica', 'degree' => 'Profesorado en Matemáticas', 'year' => 2016, 'experience' => 7, 'subjects' => ['Math', 'Statistics']],
            ['name' => 'Prof. Laura Fernandez', 'email' => 'laura.fernandez@uninorte.edu.py', 'university' => 'Universidad del Norte', 'degree' => 'Licenciatura en Educación Primaria', 'year' => 2018, 'experience' => 5, 'subjects' => ['Elementary Education', 'Art']],
            ['name' => 'Prof. Roberto Silva', 'email' => 'roberto.silva@ucsa.edu.py', 'university' => 'Universidad Columbia', 'degree' => 'Profesorado en Inglés', 'year' => 2013, 'experience' => 10, 'subjects' => ['English', 'ESL']],
            ['name' => 'Prof. Patricia Lopez', 'email' => 'patricia.lopez@uaa.edu.py', 'university' => 'Universidad Americana', 'degree' => 'Licenciatura en Historia', 'year' => 2019, 'experience' => 4, 'subjects' => ['History', 'Social Studies']],
            ['name' => 'Prof. Javier Castro', 'email' => 'javier.castro@fpuna.edu.py', 'university' => 'Universidad Nacional', 'degree' => 'Profesorado en Educación Física', 'year' => 2016, 'experience' => 7, 'subjects' => ['PE', 'Health']],
            ['name' => 'Prof. Sofia Ramirez', 'email' => 'sofia.ramirez@uca.edu.py', 'university' => 'Universidad Católica', 'degree' => 'Licenciatura en Música', 'year' => 2017, 'experience' => 6, 'subjects' => ['Music', 'Art']],
            ['name' => 'Prof. Miguel Torres', 'email' => 'miguel.torres@unae.edu.py', 'university' => 'Universidad Autónoma', 'degree' => 'Profesorado en Informática', 'year' => 2015, 'experience' => 8, 'subjects' => ['Technology', 'Computer Science']],
        ];

        foreach ($teachers as $index => $teacherData) {
            // Create user
            $user = User::create([
                'name' => $teacherData['name'],
                'email' => $teacherData['email'],
                'password' => Hash::make('password123'),
                'role' => 'participant',
                'phone' => '+595 21 ' . rand(100000, 999999),
                'date_of_birth' => now()->subYears(rand(28, 45))->format('Y-m-d'),
                'nationality' => 'Paraguayan',
            ]);

            // Create validation
            $validation = TeacherValidation::create([
                'user_id' => $user->id,
                'mec_registration_number' => $index < 7 ? 'MEC' . str_pad($user->id, 6, '0', STR_PAD_LEFT) : null,
                'has_mec_validation' => $index < 7,
                'mec_validation_date' => $index < 7 ? now()->subDays(rand(30, 90)) : null,
                'mec_status' => $index < 7 ? 'approved' : ($index < 9 ? 'pending' : 'pending'),
                'teaching_degree_title' => $teacherData['degree'],
                'university_name' => $teacherData['university'],
                'graduation_year' => $teacherData['year'],
                'diploma_apostilled' => $index < 8,
                'transcript_apostilled' => $index < 8,
                'teaching_years_total' => $teacherData['experience'],
                'teaching_years_verified' => $teacherData['experience'],
                'subjects_taught' => $teacherData['subjects'],
                'grade_levels_taught' => $index < 4 ? ['9-12', 'High School'] : ($index < 7 ? ['6-8', 'Middle School'] : ['K-5', 'Elementary']),
                'current_employment_status' => 'employed',
                'current_school_name' => 'Colegio Nacional ' . ['Central', 'San José', 'Cristo Rey', 'Técnico'][$index % 4],
                'has_tefl_certification' => $index % 3 == 0,
                'has_tesol_certification' => $index % 4 == 0,
                'other_certifications' => $index < 5 ? ['First Aid', 'Technology Integration'] : [],
                'has_criminal_record' => false,
                'criminal_record_date' => now()->subDays(rand(20, 60)),
                'has_child_abuse_clearance' => true,
                'registered_for_job_fair' => $index < 6,
                'job_fair_date' => $index < 6 ? now()->addDays(rand(10, 30)) : null,
                'job_fair_status' => $index < 6 ? 'registered' : null,
                'interviews_scheduled' => $index < 4 ? rand(2, 5) : 0,
                'offers_received' => $index < 2 ? rand(1, 3) : 0,
                'preferred_states' => ['TX', 'FL', 'CA', 'CO'][$index % 4],
                'preferred_grade_levels' => $teacherData['subjects'],
                'preferred_subjects' => $teacherData['subjects'],
                'school_type_preference' => ['public', 'private', 'charter', 'any'][$index % 4],
                'willing_to_relocate' => true,
                'validation_status' => $index < 7 ? 'approved' : ($index < 9 ? 'pending_review' : 'incomplete'),
                'validated_by' => $index < 7 ? 1 : null,
                'validation_completed_at' => $index < 7 ? now()->subDays(rand(10, 40)) : null,
            ]);
        }

        // Create job fair events
        $jobFair1 = JobFairEvent::create([
            'event_name' => 'Summer 2025 International Teacher Recruitment Fair',
            'description' => 'Annual teacher recruitment event connecting international educators with US schools.',
            'event_date' => now()->addDays(25),
            'start_time' => '09:00:00',
            'end_time' => '17:00:00',
            'event_type' => 'hybrid',
            'venue_name' => 'Austin Convention Center',
            'venue_address' => '500 East Cesar Chavez Street',
            'city' => 'Austin',
            'state' => 'TX',
            'virtual_platform' => 'Zoom',
            'meeting_link' => 'https://zoom.us/j/teacher-fair-2025',
            'max_participants' => 150,
            'registered_participants' => 42,
            'max_schools' => 50,
            'registered_schools' => 18,
            'registration_opens' => now()->subDays(30),
            'registration_closes' => now()->addDays(20),
            'status' => 'registration_open',
            'requires_mec_validation' => true,
            'requires_payment' => false,
            'required_documents' => ['CV', 'Teaching Certificate', 'Passport Copy'],
            'total_interviews' => 0,
            'total_offers' => 0,
            'successful_placements' => 0,
        ]);

        $jobFair2 = JobFairEvent::create([
            'event_name' => 'Fall 2024 Virtual Teacher Expo',
            'description' => 'Completed virtual job fair for international teachers.',
            'event_date' => now()->subDays(45),
            'start_time' => '10:00:00',
            'end_time' => '16:00:00',
            'event_type' => 'virtual',
            'virtual_platform' => 'Microsoft Teams',
            'meeting_link' => 'https://teams.microsoft.com/teacher-expo-fall',
            'max_participants' => 100,
            'registered_participants' => 87,
            'max_schools' => 30,
            'registered_schools' => 24,
            'registration_opens' => now()->subDays(90),
            'registration_closes' => now()->subDays(50),
            'status' => 'completed',
            'requires_mec_validation' => true,
            'requires_payment' => false,
            'required_documents' => ['Resume', 'Certifications'],
            'total_interviews' => 186,
            'total_offers' => 45,
            'successful_placements' => 28,
        ]);

        $this->command->info('Teacher seeder completed successfully!');
        $this->command->info('Created: ' . count($createdSchools) . ' schools, ' . count($teachers) . ' teachers, 2 job fairs');
    }
}
